INSERT INTO `categorias` (`nombre`, `created_at`, `updated_at`) VALUES 
('Carnes/Aves/Embutidos', now(), now()),
('Aceite/Grasa', now(), now()),
('Bases cocina', now(), now()),
('Bebidas', now(), now()),
('Condim/Espec/Hierbas', now(), now()),
('Conservas', now(), now()),
('Consumibles', now(), now()),
('Frutas/Frutos Secos', now(), now()),
('Hortalizas', now(), now()),
('Huevos', now(), now()),
('Lacteos y derivados', now(), now()),
('Pastas Alimenticias', now(), now()),
('Legumb/Cereal/Pan/Boller', now(), now()),
('Pastelería', now(), now()),
('Pescados/Mariscos', now(), now()),
('Cafés/Infus', now(), now()),